parameters:
#    cyclone_component_mail.example.class: Cyclone\Component\MailBundle\Example

services:
#    cyclone_component_mail.example:
#        class: %cyclone_component_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
