imports:
    - { resource: parameters.yml }

services:
#    cyclone_component_mail.example:
#        class: %cyclone_component_mail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
